FROM ubuntu:latest

RUN apt-get update
RUN apt-get install -y \
    dnsutils \
    curl \
    iftop \
    vnstat \
    hping3 \
    nmap \
    tcpdump \
    wget
RUN	apt-get clean && rm -rf /var/lib/apt/lists
